makeAll: 
	gcc -o uniqueUnsorted unique.c unsorted.c
	gcc -o bincountUnsorted bincount.c unsorted.c
	gcc -o parityUnsorted parity.c unsorted.c
	gcc -o uniqueSorted unique.c sorted.c
	gcc -o bincountSorted bincount.c sorted.c
	gcc -o paritySorted parity.c sorted.c

